spring:
  datasource:
    url: jdbc:sqlserver://property-management.database.windows.net:1433;database=property-management-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: propertymanagementadmin@property-management
    password: Test#8055
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true

server:
  port: 8080